export { LoginPage } from "./LoginPage";
export { DashboardPage } from "./DashboardPage";
export { AttendancePage } from "./AttendancePage";
export { PayrollPage } from "./PayrollPage";
export { KPIPage } from "./KPIPage";
export { EmployeesPage } from "./EmployeesPage";
export { HiringPage } from "./HiringPage";
export { LeavePage } from "./LeavePage";
export { SettingsPage } from "./SettingsPage";